### ISSUE TITLE
Custom tokens not replaced correctly

### ISSUE THREAD

**Issue by waddyvic** [CiviCooP/org.civicoop.emailapi#10] opened 2017-06-06 17:21 UTC
Tested this extension v1.10 on CiviCRM 4.5.5.

We developed a custom extension to add extra tokens to email templates. However, when sending email using this api, the extra tokens did not get replaced properly.

Comparing api/v3/Email/Send.php and Civi's core CRM/Core/BAO/MessageTemplate.php->sendTemplate(), the way api/v3/Email/Send.php to send email is significantly different. There are extra steps in MessageTemplate::sendTemplate() to get tokens and their values, which I don't see in Send.php. Maybe this caused Send.php to lose some tokens when sending email?

**Comment by jaapjansma** [comment] 2017-06-06 17:40
The original email api is copied from civicrm core code version 4.4 and later updated to 4.6.
Feel free to update the code so that custom tokens are parsed. Probably with an if statement for version comparison so that extension keeps working on 4.6 and later.  
You can update the code by forking this repo and sending in a Pull request.

**Comment by waddyvic** [comment] 2017-06-06 19:53
@jaapjansma OK great. Could you tell me which core classes are copied from?

**Comment by jaapjansma** [comment] 2017-06-07 07:21
From here https://github.com/civicrm/civicrm-core/blob/4.6/CRM/Contact/Form/Task/EmailCommon.php#L375 and https://github.com/civicrm/civicrm-core/blob/4.6/CRM/Activity/BAO/Activity.php#L1185
I had to combine some functions from core code.

**Comment by twomice** [comment] 2018-07-23 20:23
FYI, still an issue in v 1.17.2. (Interestingly, it works fine for me in v 1.10, CiviCRM 4.7.30).

**Comment by systopia** [comment] 2018-08-06 15:07
Hi @jaapjansma.

I (think I) have the same issues with custom tokens. When my ``civicrm_tokenValues`` hook is called from the "Send an Email" action, the values look like this:
```
$cids = ["299514"]
$job = null
$values = {"299514":{"contact_id":"299514","do_not_email":"0",[...],"on_hold":"0"}}
```
Whereas when I use your ``Email.send`` API action it looks as follows:
```
$cids = "299514"
$job = NULL
$values = {"contact_id":"299514","contact_type":"Individual","contact_sub_type",[...],"country":null}
```
The difference in ``$cids`` is not so bad, because I think other subsystems do this "collapse into string" part as well, but the missing level in ``$values`` really throws me off.

If you agree, I can post a PR, it seems like it's a small adjustment to https://github.com/CiviCooP/org.civicoop.emailapi/blob/1.17/api/v3/Email/Send.php#L164

**Comment by jaapjansma** [comment] 2018-08-06 15:09
@systopia a PR is really welcome. Looks like you have done some good analyses of the problem.

**Comment by rrooij** [comment] 2018-10-05 10:46
I created a small fix.
https://github.com/SPnl/org.civicoop.emailapi/commit/2a8e16d00bcabbfb1a1729805afcfd77308ba870

However, I only tested it on contact tokens. I don't know whether other tokens still work.

**Comment by jaapjansma** [comment] 2018-10-21 18:20
There is also a fix in PR #28 which is merged by now.

**Comment by Edzelopez** [comment] 2018-10-23 11:36
FWIW, I have the latest version of this extension and my custom tokens aren't being replaced as well. I am using [this](https://wiki.civicrm.org/confluence/display/CRMDOC/Customized+%28and+Custom%29+Tokens) guide to create my custom tokens.

**Comment by jaapjansma** [comment] 2018-10-24 09:48
@Edzelopez could you check against the master branch?  Because the latest release does not contain the merged Pull requests.

**Comment by mol3earth** [comment] 2018-10-24 12:06
we upgraded to 4.6.38 from 4.6.34 over the weekend and contact tokens stopped working in email api for us. 
these are not custom tokens. e.g. contact_id doesn't work

**Comment by Edzelopez** [comment] 2018-10-24 12:21
Thanks for your reply @jaapjansma!
I can confirm I'm using the master branch and can also verify that the tokens are being replaced correctly in my hook. The token is replaced by a blank string in this line https://github.com/CiviCooP/org.civicoop.emailapi/blob/master/api/v3/Email/Send.php#L187

**Comment by jaapjansma** [comment] 2018-10-26 08:39
@Edzelopez I have also merged the fix from @twomice could you test again against the master branch? And confirm whether it is working/not working now?

**Comment by jaapjansma** [comment] 2018-11-06 06:48
@Edzelopez and @twomice I have debugged this issue and I think I have solved it, at least it is working for me with civicrm version 5.4.0. Could you test it again with the master branch?

The bug was introduced by the fix provided @rrooij, so I have reverted his changes and then it worked again.

**Comment by Edzelopez** [comment] 2018-11-12 11:12
Sorry for the delay @jaapjansma, I was on vacation for the last week. I can confirm as well that the issue is fixed in the master branch for me. Thanks for the quick action and the work done in this extension!

**Comment by radiomariaargentina** [comment] 2018-12-03 16:30
I do not work with custom tokens. Installed version: 1.17.2

**Comment by otetard** [comment] 2019-01-14 15:37
In my installation, the current code (1.18) of EmailAPI isn’t working for basic tokens like ` {contact.first_name}` (as mentioned by @magnolia61).

To solve that issue, I’ve applied the following modification https://github.com/otetard/org.civicoop.emailapi/commit/4152dad05a65cceb4829947d02670305e22c7856 to my code base. _In my situation_, it works fine now.

**Comment by haraldballuch** [comment] 2019-02-15 13:12
In version 1.19 I have the problem, that tokens (at least hook tokens) are not replaced in the subject. As far as I can remember, this never worked in any Emailapi version I used.

So I made fix, that does the trick at least in my configuration now. It replaces contact, hook and domain tokens in subject, html and text. I didn't test the contribution tokens because I don't have experience with them and the module is not activated here. And to be honest I don't know what component tokens are? Do they make sense in this context? Anyway I left the call to replaceComponentTokens in the code, although I don't know if it has any sense or if it works, as it doesn't seem to harm in my case.

I removed the call of replaceGreetingTokens because this function seems deprecated to me. But maybe it has some sense for backward compatibility? I don't know. But as far as I can tell from to code it seems to replace contact and hook tokens. But as there are specific functions that do this (replaceContactTokens  and replaceHookTokens) and they are already called in the code, this function seems to have no sense to me, but throwing PHP warnings about wrong parameters.

The only other change is to create an array for each contact before calling the replace functions, that is built in a way how the replace functions expect this array to be, by using getTokenDetails.

You can see the code changes here:  https://github.com/haraldballuch/org.civicoop.emailapi/commit/6d32e1ded92efe39f6498f8ffd3a0d0f53a79e04

**Comment by magnolia61** [comment] 2019-08-11 10:52
Hi all. After reading some of the issues here I am confused about which tokens are and which aren't supposed to be replaced.
a) contact tokens
b) custom contact tokens
c) contribution tokens (in contribution related mails)
d) custom contribution tokens (in contribution related mails)
e) participant tokens (in event registration related mails)
f) custom participant tokens (in event registration related mails)

I have the assumption only a) & b) are supported to work at the moment. And they should work in both the body and subject. Am I right with my assumption?

**Comment by jaapjansma** [comment] 2019-08-22 13:14
I have just tested this with CiviRules (version 2.9), E-mail api (version 1.19,  nz.co.fuzion.civitoken (version 1.4) and CiviCRM version 5.13alpha1

The conclusion is general speaking that only the contact tokens are working.

**On a contact is added trigger**:
I have tested the following tokens
`{contact.id}`: **works**
`{contact.display_name}`: **works**
`{contact.custom_1}`: **works**
`{relationships.display_name_5_a_b}` : **works**

**On an activity is added trigger**:
I have tested the following tokens:
`{contact.id}`: **works**
`{contact.display_name}`: **works**
`{contact.custom_1}`: **works**
`{relationships.display_name_5_a_b}` : **works**
`{activity.id}`: **Does not work**
`{activity.subject}`: **Does not work**
`{activity.custom_2}`: **Does not work**

**On an contribution is added trigger**:
I have tested the following tokens:
`{contact.id}`: **works**
`{contact.display_name}`: **works**
`{contact.custom_1}`: **works**
`{relationships.display_name_5_a_b}` : **works**
`{contribution.id}`: **Works**
`{contribution.total_amount}`: **Works**
`{contribution.custom_3}`: **Does not work**

**On an custom data on case is changed trigger**:
I have tested the following tokens:
`{contact.id}`: **works**
`{contact.display_name}`: **works**
`{contact.custom_1}`: **works**
`{relationships.display_name_5_a_b}` : **works**
`{case.id}`: **Does not work**
`{case.subject}` **Does not work**
`{case.custom_4}`: **Does not work**

**Comment by jaapjansma** [comment] 2019-08-22 13:15
Because the contact tokens work I will close this issue.

**Closed by jaapjansma** 2019-08-22 13:15 UTC

**Comment by jaapjansma** [comment] 2019-08-22 13:22
I have also fixed the replacements of contact tokens in the subject of the e-mail.
